import { guardrailLogoMap } from "./guardrail_info_helpers";

export interface GuardrailCardInfo {
  id: string;
  name: string;
  description: string;
  category: "litellm" | "partner";
  subcategory?: string;
  logo: string;
  tags: string[];
  eval?: {
    f1: number;
    precision: number;
    recall: number;
    testCases: number;
    latency: string;
  };
  providerKey?: string;
}

const litellmContentFilterLogo = guardrailLogoMap["LiteLLM Content Filter"];

export const LITELLM_CONTENT_FILTER_CARDS: GuardrailCardInfo[] = [
  {
    id: "cf_denied_financial",
    name: "Denied Financial Advice",
    description:
      "Определяет запросы персональных финансовых консультаций, инвестиционных рекомендаций или финансового планирования.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Topic Blocker"],
    eval: {
      f1: 100.0,
      precision: 100.0,
      recall: 100.0,
      testCases: 207,
      latency: "<0.1ms",
    },
  },
  {
    id: "cf_denied_insults",
    name: "Insults & Personal Attacks",
    description: "Определяет оскорбления, ругань и личные выпады в адрес чат-бота, сотрудников или других людей.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Topic Blocker"],
    eval: {
      f1: 100.0,
      precision: 100.0,
      recall: 100.0,
      testCases: 299,
      latency: "<0.1ms",
    },
  },
  {
    id: "cf_denied_legal",
    name: "Denied Legal Advice",
    description: "Определяет запросы несанкционированной юридической консультации, разбора дела или правовых рекомендаций.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Topic Blocker"],
  },
  {
    id: "cf_denied_medical",
    name: "Denied Medical Advice",
    description: "Определяет запросы медицинского диагноза, рекомендаций по лечению или советов о здоровье.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Topic Blocker"],
  },
  {
    id: "cf_harmful_violence",
    name: "Harmful Violence",
    description: "Определяет контент, связанный с насилием, преступным планированием, нападениями и угрозами.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Safety"],
  },
  {
    id: "cf_harmful_self_harm",
    name: "Harmful Self-Harm",
    description: "Определяет контент, связанный с самоповреждением, суицидом и опасным саморазрушительным поведением.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Safety"],
  },
  {
    id: "cf_harmful_child_safety",
    name: "Harmful Child Safety",
    description: "Определяет контент, способный угрожать безопасности детей или эксплуатации несовершеннолетних.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Safety"],
  },
  {
    id: "cf_harmful_illegal_weapons",
    name: "Harmful Illegal Weapons",
    description: "Определяет контент, связанный с незаконным изготовлением, распространением или приобретением оружия.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Safety"],
  },
  {
    id: "cf_bias_gender",
    name: "Bias: Gender",
    description: "Определяет гендерную дискриминацию, стереотипы и предвзятые формулировки.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Bias"],
  },
  {
    id: "cf_bias_racial",
    name: "Bias: Racial",
    description: "Определяет расовую дискриминацию, стереотипы и расово предвзятый контент.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Bias"],
  },
  {
    id: "cf_bias_religious",
    name: "Bias: Religious",
    description: "Определяет религиозную дискриминацию, нетерпимость и религиозно предвзятый контент.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Bias"],
  },
  {
    id: "cf_bias_sexual_orientation",
    name: "Bias: Sexual Orientation",
    description: "Определяет дискриминацию по признаку ориентации и связанный предвзятый контент.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Bias"],
  },
  {
    id: "cf_prompt_injection_jailbreak",
    name: "Prompt Injection: Jailbreak",
    description: "Определяет попытки джейлбрейка в обход правил безопасности ИИ и ограничений.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Prompt Injection"],
  },
  {
    id: "cf_prompt_injection_data_exfil",
    name: "Prompt Injection: Data Exfiltration",
    description: "Определяет попытки извлечь чувствительные данные манипуляцией промптом.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Prompt Injection"],
  },
  {
    id: "cf_prompt_injection_sql",
    name: "Prompt Injection: SQL",
    description: "Определяет SQL-инъекции, встроенные в промпты.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Prompt Injection"],
  },
  {
    id: "cf_prompt_injection_malicious_code",
    name: "Prompt Injection: Malicious Code",
    description: "Определяет попытки внедрить вредоносный код через промпты.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Prompt Injection"],
  },
  {
    id: "cf_prompt_injection_system_prompt",
    name: "Prompt Injection: System Prompt",
    description: "Определяет попытки извлечь или перезаписать системные промпты.",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Prompt Injection"],
  },
  {
    id: "cf_toxic_abuse",
    name: "Toxic & Abusive Language",
    description: "Определяет токсичный, оскорбительный и ненавистнический язык на нескольких языках (EN, AU, DE, ES, FR).",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Toxicity"],
  },
  {
    id: "cf_patterns",
    name: "Pattern Matching",
    description:
      "Обнаруживает и блокирует образцы чувствительных данных: СНИЛС/SSN, номера карт, API-ключи и пользовательские regex.",
    category: "litellm",
    subcategory: "Patterns",
    logo: litellmContentFilterLogo,
    tags: ["PII", "Regex", "Data Protection"],
  },
  {
    id: "cf_keywords",
    name: "Keyword Blocking",
    description:
      "Блокирует или маскирует контент с заданными словами или фразами. Загрузите свой список слов или добавьте отдельные термины.",
    category: "litellm",
    subcategory: "Keywords",
    logo: litellmContentFilterLogo,
    tags: ["Keywords", "Blocklist"],
  },
  {
    id: "block_code_execution",
    name: "Block Code Execution",
    description:
      "Определяет fenced-блоки кода markdown в запросах и ответах. Блокирует или маскирует исполняемый код (Python, JavaScript, Bash) по языку с настраиваемой уверенностью.",
    category: "litellm",
    subcategory: "Code Safety",
    logo: litellmContentFilterLogo,
    tags: ["Code", "Safety", "Prompt Injection"],
  },
  {
    id: "cf_competitor_intent",
    name: "Competitor Name Blocking",
    description:
      "Блокирует или переформулирует намерение сравнить конкурентов. Определяет запросы сравнения или рекомендаций конкурентов (авиакомпании или общие списки).",
    category: "litellm",
    subcategory: "Content Category",
    logo: litellmContentFilterLogo,
    tags: ["Content Category", "Competitor", "Topic Blocker"],
  },
];

export const PARTNER_GUARDRAIL_CARDS: GuardrailCardInfo[] = [
  {
    id: "presidio",
    name: "Presidio PII",
    description:
      "Microsoft Presidio для обнаружения и анонимизации PII. Более 30 типов сущностей с настраиваемыми действиями.",
    category: "partner",
    logo: guardrailLogoMap["Presidio PII"],
    tags: ["PII", "Microsoft"],
    providerKey: "PresidioPII",
  },
  {
    id: "bedrock",
    name: "Bedrock Guardrail",
    description: "AWS Bedrock Guardrails: фильтрация контента, обход тем и обнаружение чувствительной информации.",
    category: "partner",
    logo: guardrailLogoMap["Bedrock Guardrail"],
    tags: ["AWS", "Content Safety"],
    providerKey: "Bedrock",
  },
  {
    id: "lakera",
    name: "Lakera",
    description: "Платформа безопасности ИИ: защита от инъекций промпта, утечек данных и вредного контента.",
    category: "partner",
    logo: guardrailLogoMap["Lakera"],
    tags: ["Security", "Prompt Injection"],
    providerKey: "Lakera",
  },
  {
    id: "openai_moderation",
    name: "OpenAI Moderation",
    description: "API модерации контента OpenAI для обнаружения вредного контента по многим категориям.",
    category: "partner",
    logo: guardrailLogoMap["OpenAI Moderation"],
    tags: ["Content Moderation", "OpenAI"],
  },
  {
    id: "google_model_armor",
    name: "Google Cloud Model Armor",
    description: "Сервис защиты моделей Google Cloud для безопасного и ответственного внедрения ИИ.",
    category: "partner",
    logo: guardrailLogoMap["Google Cloud Model Armor"],
    tags: ["Google Cloud", "Safety"],
  },
  {
    id: "guardrails_ai",
    name: "Guardrails AI",
    description: "Открытый фреймворк структурных, типовых и качественных гарантий для ответов LLM.",
    category: "partner",
    logo: guardrailLogoMap["Guardrails AI"],
    tags: ["Open Source", "Validation"],
  },
  {
    id: "zscaler",
    name: "Zscaler AI Guard",
    description: "Корпоративная безопасность ИИ от Zscaler: мониторинг и защита AI/ML-нагрузок.",
    category: "partner",
    logo: guardrailLogoMap["Zscaler AI Guard"],
    tags: ["Enterprise", "Security"],
  },
  {
    id: "panw",
    name: "PANW Prisma AIRS",
    description: "Palo Alto Networks Prisma AI Runtime Security — защита ИИ-приложений в проде.",
    category: "partner",
    logo: guardrailLogoMap["PANW Prisma AIRS"],
    tags: ["Enterprise", "Security"],
  },
  {
    id: "cisco_ai_defense",
    name: "Cisco AI Defense",
    description:
      "API инспекции Cisco AI Defense для защиты во время работы: инъекции промпта, PII/PCI/PHI, домогательства, ненависть, нецензурщина, насилие, код.",
    category: "partner",
    logo: guardrailLogoMap["Cisco AI Defense"],
    tags: ["Enterprise", "Security", "Prompt Injection", "PII"],
    providerKey: "CiscoAiDefense",
  },
  {
    id: "noma",
    name: "Noma Security",
    description: "Платформа безопасности ИИ для обнаружения и предотвращения ИИ-специфичных угроз и уязвимостей.",
    category: "partner",
    logo: guardrailLogoMap["Noma Security"],
    tags: ["Security", "Threat Detection"],
  },
  {
    id: "aporia",
    name: "Aporia AI",
    description: "Гардрейлы ИИ в реальном времени: обнаружение галлюцинаций, контроль тем, соблюдение политик.",
    category: "partner",
    logo: guardrailLogoMap["Aporia AI"],
    tags: ["Hallucination", "Policy"],
  },
  {
    id: "aim",
    name: "AIM Guardrail",
    description: "Гардрейлы AIM Security: комплексное обнаружение и снижение ИИ-угроз.",
    category: "partner",
    logo: guardrailLogoMap["AIM Guardrail"],
    tags: ["Security", "Threat Detection"],
  },
  {
    id: "cato_networks",
    name: "Cato Networks Guardrail",
    description: "Гардрейлы Cato Networks: комплексное обнаружение и снижение ИИ-угроз.",
    category: "partner",
    logo: guardrailLogoMap["Cato Networks Guardrail"],
    tags: ["Security", "Threat Detection"],
  },
  {
    id: "prompt_security",
    name: "Prompt Security",
    description: "Защита от инъекций промпта, утечек данных и прочих угроз безопасности LLM.",
    category: "partner",
    logo: guardrailLogoMap["Prompt Security"],
    tags: ["Prompt Injection", "Security"],
  },
  {
    id: "lasso",
    name: "Lasso Guardrail",
    description: "Модерация контента и гардрейлы безопасности для ответственного внедрения ИИ.",
    category: "partner",
    logo: guardrailLogoMap["Lasso Guardrail"],
    tags: ["Content Moderation"],
  },
  {
    id: "pangea",
    name: "Pangea Guardrail",
    description: "Гардрейлы Pangea для безопасных, соответствующих требованиям и надёжных ИИ-приложений.",
    category: "partner",
    logo: guardrailLogoMap["Pangea Guardrail"],
    tags: ["Compliance", "Security"],
  },
  {
    id: "enkryptai",
    name: "EnkryptAI",
    description: "Платформа безопасности и управления ИИ для корпоративной безопасности и соответствия.",
    category: "partner",
    logo: guardrailLogoMap["EnkryptAI"],
    tags: ["Enterprise", "Governance"],
  },
  {
    id: "javelin",
    name: "Javelin Guardrails",
    description: "ИИ-шлюз со встроенными гардрейлами для безопасной и соответствующей работы ИИ.",
    category: "partner",
    logo: guardrailLogoMap["Javelin Guardrails"],
    tags: ["Gateway", "Security"],
  },
  {
    id: "pillar",
    name: "Pillar Guardrail",
    description: "Платформа безопасности ИИ для мониторинга, тестирования и защиты ИИ-систем.",
    category: "partner",
    logo: guardrailLogoMap["Pillar Guardrail"],
    tags: ["Monitoring", "Safety"],
  },
  {
    id: "akto",
    name: "Akto Guardrail",
    description: "Платформа безопасности ИИ от Akto.io: автоматический мониторинг и гардрейлы для AI/ML-приложений.",
    category: "partner",
    logo: guardrailLogoMap["Akto"],
    tags: ["Security", "Safety", "Monitoring"],
  },
  {
    id: "promptguard",
    name: "PromptGuard",
    description:
      "ИИ-шлюз безопасности: инъекции промпта, редактирование PII, фильтр тем, блэклисты сущностей, обнаружение галлюцинаций. Самостоятельный хостинг, интеграция в прокси без изменений.",
    category: "partner",
    logo: guardrailLogoMap["PromptGuard"],
    tags: ["Security", "Prompt Injection", "PII"],
    providerKey: "Promptguard",
    eval: {
      f1: 94.9,
      precision: 100.0,
      recall: 90.4,
      testCases: 5384,
      latency: "~150ms",
    },
  },
  {
    id: "xecguard",
    name: "XecGuard",
    description:
      "ИИ-шлюз безопасности CyCraft XecGuard. Мультиполитичное сканирование (инъекции, вредный контент, PII, системный промпт) плюс привязка к контексту RAG.",
    category: "partner",
    logo: guardrailLogoMap["XecGuard"],
    tags: ["Security", "Policy", "Grounding", "RAG"],
    providerKey: "Xecguard",
  },
  {
    id: "deepkeep",
    name: "DeepKeep AI Firewall",
    description:
      "DeepKeep AI Firewall для комплексной безопасности LLM: инъекции промпта, защита PII, модерация контента, соблюдение политик с настраиваемыми конвейерами гардрейлов.",
    category: "partner",
    logo: guardrailLogoMap["DeepKeep AI Firewall"],
    tags: ["Security", "Prompt Injection", "PII", "Firewall"],
    providerKey: "Deepkeep",
  },
  {
    id: "repelloai",
    name: "RepelloAI Argus",
    description:
      "RepelloAI Argus проверяет промпты и ответы по политикам, настроенным для каждого актива в панели Repello.",
    category: "partner",
    logo: guardrailLogoMap["RepelloAI Argus"],
    tags: ["Security", "Policy", "Prompt Injection"],
    providerKey: "Repelloai",
  },
  {
    id: "straiker",
    name: "Straiker",
    description:
      "Agentic-гардрейлы Defend AI: непрямые/прямые инъекции промпта, злоупотребление инструментами, вредоносные MCP и навыки.",
    category: "partner",
    logo: guardrailLogoMap["Straiker"],
    tags: ["Agentic", "Prompt Injection", "Tool Misuse", "MCP", "Skills"],
    providerKey: "Straiker",
  },
  {
    id: "alice",
    name: "Alice",
    description:
      "Гардрейлы на политиках для промптов и ответов модели, оцениваемые по приложениям: один прокси может применять свой набор политик для каждой команды или продукта.",
    category: "partner",
    logo: guardrailLogoMap["Alice"],
    tags: ["Content Moderation", "Prompt Injection", "PII", "Policy"],
    providerKey: "Alice",
  },
  {
    id: "conduct",
    name: "Conduct Guard",
    description:
      "Conduct Guard проверяет промпты по правилам рабочего пространства до вызова модели: инъекции, PII и пользовательские политики, с вердиктами блокировки, предупреждения и одобрения.",
    category: "partner",
    logo: guardrailLogoMap["Conduct Guard"],
    tags: ["Security", "Prompt Injection", "PII", "Policy"],
    providerKey: "Conduct",
  },
];

export const ALL_CARDS = [...LITELLM_CONTENT_FILTER_CARDS, ...PARTNER_GUARDRAIL_CARDS];
