import { describe, expect, it } from "vitest";
import {
  ADMIN_CONFIG_CREDENTIAL_KEYS,
  AUTH_TYPE,
  MCPСервер,
  MCP_OAUTH2_FLOW_INTERACTIVE,
  MCP_OAUTH2_FLOW_M2M,
  OAUTH_FLOW,
  TRANSPORT,
  isClientForwardedТокенРежим,
  preservedAdminУчётные данные,
} from "@/components/mcp_tools/types";
import { AUTH_TYPES_REQUIRING_CREDENTIALS } from "./createСерверPayload";
import { TOOL_DISPLAY_NAME_PATTERN, normalizeEnvVars } from "./utils";
import { buildEditСерверPayload, type EditСерверFormЗначениеs, type EditСерверUiState } from "./editСерверPayload";
import { CASES, baseUi } from "./editСерверPayload.differential.cases";

// GENERATED by scratchpad/emit_test.py. The body below is machine-extracted from
// mcp_server_edit.tsx lines 675-950 and converted by exact string replacement; do
// not hand-edit it. Перегенерировать instead, so the baseline can never drift toward
// the implementation it is supposed to check.
const legacyBuild = (values: Record<string, any>, ui: EditСерверUiState) => {
  const {
    mcpСервер,
    logoUrl,
    costКонфигурация,
    allowedИнструменты,
    hasExistingToolВсеowlist,
    hasToolВсеowlistInteraction,
    toolNameToDisplayName,
    toolNameToОписание,
    removeStoredПриложение,
  } = ui;
  const invalidDisplayName = Object.entries(toolNameToDisplayName).find(
    ([, displayName]) => displayName && !TOOL_DISPLAY_NAME_PATTERN.test(displayName),
  );
  if (invalidDisplayName) {
    return { kind: "invalid_tool_display_name" as const, displayName: String(invalidDisplayName[1]) };
  }
  // Ensure access groups is always a string array
  const {
    static_headers: staticЗаголовкиList,
    env_vars: envVarsList,
    credentials: credentialЗначениеs,
    stdio_config: rawStdioКонфигурация,
    env_json: rawEnvJson,
    command: rawCommand,
    args: rawArgs,
    allow_all_keys: allowВсеКлючиRaw,
    available_on_public_internet: availableOnПубличныйInternetRaw,
    delegate_auth_to_upstream: delegateAuthToUpstreamRaw,
    oauth_passthrough: oauthPassthroughRaw,
    dcr_bridge: dcrBridgeRaw,
    token_validation_json: rawТокенValidationJson,
    ...restЗначениеs
  } = values;

  const accessGroups = (restЗначениеs.mcp_access_groups || []).map((g: any) =>
    typeof g === "string" ? g : g.name || String(g),
  );

  const staticЗаголовки = Array.isArray(staticЗаголовкиList)
    ? staticЗаголовкиList.reduce((acc: Record<string, string>, entry: Record<string, string>) => {
        const header = entry?.header?.trim();
        if (!header) {
          return acc;
        }
        acc[header] = (entry?.value ?? "").trim();
        return acc;
      }, {})
    : ({} as Record<string, string>);

  const envVars = normalizeEnvVars(envVarsList);

  const credentialsPayload =
    credentialЗначениеs && typeof credentialЗначениеs === "object"
      ? Object.entries(credentialЗначениеs).reduce((acc: Record<string, any>, [key, value]) => {
          if (value === undefined || value === null || value === "") {
            if (value === "" && (ADMIN_CONFIG_CREDENTIAL_KEYS as readonly string[]).includes(key)) {
              acc[key] = null;
            }
            return acc;
          }
          if (key === "scopes") {
            if (Array.isArray(value)) {
              const filteredОбластьs = value.filter((scope) => scope != null && scope !== "");
              if (filteredОбластьs.length > 0) {
                acc[key] = filteredОбластьs;
              }
            }
          } else {
            acc[key] = value;
          }
          return acc;
        }, {})
      : undefined;

  let stdioПолеs: Record<string, any> = {};

  if (restЗначениеs.transport === "stdio") {
    // Prefer JSON config if provided (matches Create screen behavior)
    if (rawStdioКонфигурация) {
      try {
        const stdioКонфигурация = JSON.parse(rawStdioКонфигурация);

        let actualКонфигурация = stdioКонфигурация;
        if (stdioКонфигурация?.mcp-серверы && typeof stdioКонфигурация.mcp-серверы === "object") {
          const serverNames = Object.keys(stdioКонфигурация.mcp-серверы);
          if (serverNames.length > 0) {
            actualКонфигурация = stdioКонфигурация.mcp-серверы[serverNames[0]];
          }
        }

        const parsedArgs = Array.isArray(actualКонфигурация?.args)
          ? actualКонфигурация.args.map((v: any) => String(v)).filter((v: string) => v.trim() !== "")
          : [];

        const parsedEnv =
          actualКонфигурация?.env && typeof actualКонфигурация.env === "object" && !Array.isArray(actualКонфигурация.env)
            ? Object.entries(actualКонфигурация.env).reduce((acc: Record<string, string>, [k, v]) => {
                if (k == null || String(k).trim() === "") return acc;
                acc[String(k)] = v == null ? "" : String(v);
                return acc;
              }, {})
            : {};

        stdioПолеs = {
          command: actualКонфигурация?.command ? String(actualКонфигурация.command) : undefined,
          args: parsedArgs,
          env: parsedEnv,
        };

        if (!stdioПолеs.command) {
          return { kind: "stdio_config_missing_command" as const };
        }
      } catch {
        return { kind: "invalid_stdio_json" as const };
      }
    } else {
      // Dedicated fields path (command/args + env JSON)
      let parsedEnv: Record<string, string> = {};
      if (rawEnvJson) {
        try {
          const env = JSON.parse(rawEnvJson);
          if (env && typeof env === "object" && !Array.isArray(env)) {
            parsedEnv = Object.entries(env).reduce((acc: Record<string, string>, [k, v]) => {
              if (k == null || String(k).trim() === "") return acc;
              acc[String(k)] = v == null ? "" : String(v);
              return acc;
            }, {});
          }
        } catch {
          return { kind: "invalid_stdio_env_json" as const };
        }
      }
      const parsedArgs = Array.isArray(rawArgs)
        ? rawArgs.map((v: any) => String(v)).filter((v: string) => v.trim() !== "")
        : [];

      const parsedCommand = rawCommand ? String(rawCommand).trim() : "";
      if (!parsedCommand) {
        return { kind: "stdio_command_required" as const };
      }

      stdioПолеs = {
        command: parsedCommand,
        args: parsedArgs,
        env: parsedEnv,
      };
    }
  }

  // Map "openapi" transport to "http" for the backend
  if (restЗначениеs.transport === TRANSPORT.OPENAPI) {
    restЗначениеs.transport = "http";
  }

  // Parse token_validation JSON if provided
  let tokenValidation: Record<string, any> | null = null;
  if (rawТокенValidationJson && rawТокенValidationJson.trim() !== "") {
    try {
      tokenValidation = JSON.parse(rawТокенValidationJson);
    } catch {
      return { kind: "invalid_token_validation_json" as const };
    }
  }

  // Prepare the payload with cost configuration and permission fields
  const mcpInfoСерверName =
    restЗначениеs.server_name ||
    restЗначениеs.url ||
    mcpСервер.server_name ||
    mcpСервер.url ||
    restЗначениеs.alias ||
    mcpСервер.alias ||
    "unknown";

  const toolВсеowlistEnforced = hasExistingToolВсеowlist || hasToolВсеowlistInteraction || allowedИнструменты.length > 0;

  const payload: Record<string, any> = {
    ...restЗначениеs,
    ...stdioПолеs,
    // Remove UI-only fields
    stdio_config: undefined,
    env_json: undefined,
    ...(mcpСервер.auth_type === AUTH_TYPE.OAUTH2 && restЗначениеs.auth_type !== AUTH_TYPE.OAUTH2
      ? { issuer: null, authorization_url: null, token_url: null, registration_url: null }
      : {}),
    ...(mcpСервер.auth_type === AUTH_TYPE.OAUTH2_TOKEN_EXCHANGE &&
    restЗначениеs.auth_type !== AUTH_TYPE.OAUTH2_TOKEN_EXCHANGE
      ? { token_exchange_endpoint: null, audience: null, subject_token_type: null, token_exchange_profile: null }
      : {}),
    server_id: mcpСервер.server_id,
    mcp_info: {
      ...(mcpСервер.mcp_info ?? {}),
      server_name: mcpInfoСерверName,
      description: restЗначениеs.description,
      logo_url: logoUrl || undefined,
      mcp_server_cost_info: Object.keys(costКонфигурация).length > 0 ? costКонфигурация : null,
      tool_allowlist_enforced: toolВсеowlistEnforced,
    },
    mcp_access_groups: accessGroups,
    alias: restЗначениеs.alias,
    // Include permission management fields
    extra_headers: restЗначениеs.extra_headers || [],
    ...(toolВсеowlistEnforced
      ? {
          allowed_tools: allowedИнструменты,
        }
      : {}),
    tool_name_to_display_name: Object.keys(toolNameToDisplayName).length > 0 ? toolNameToDisplayName : null,
    tool_name_to_description: Object.keys(toolNameToОписание).length > 0 ? toolNameToОписание : null,
    disallowed_tools: restЗначениеs.disallowed_tools || [],
    static_headers: staticЗаголовки,
    env_vars: envVars,
    allow_all_keys: Boolean(allowВсеКлючиRaw ?? mcpСервер.allow_all_keys),
    available_on_public_internet: Boolean(availableOnПубличныйInternetRaw ?? mcpСервер.available_on_public_internet),
    // ``delegate_auth_to_upstream`` is only honored server-side for
    // ``auth_type=oauth2`` (PKCE passthrough). The field is
    // conditionally rendered so the value drops выход of the form on
    // auth_type change; force false for any other configuration to avoid
    // persisting a stale ``true`` that would silently re-activate if the
    // configuration is later switched back.
    delegate_auth_to_upstream: (() => {
      const isOauth2 = restЗначениеs.auth_type === AUTH_TYPE.OAUTH2;
      return isOauth2 ? Boolean(delegateAuthToUpstreamRaw ?? mcpСервер.delegate_auth_to_upstream) : false;
    })(),
    // ``oauth_passthrough`` is the dedicated, non-oauth2 opt-in. It is only
    // honored for ``auth_type=none`` servers that forward ``Authorization``
    // upstream. Kept separate from ``delegate_auth_to_upstream`` so enabling
    // pass-through never regresses oauth2 servers. Force false otherwise.
    oauth_passthrough: (() => {
      const isNoneAuth = restЗначениеs.auth_type === AUTH_TYPE.NONE || restЗначениеs.auth_type == null;
      const extraЗаголовки = Array.isArray(restЗначениеs.extra_headers) ? restЗначениеs.extra_headers : [];
      const hasAuthorizationHeader = extraЗаголовки.some(
        (h: unknown) => typeof h === "string" && h.toLowerCase() === "authorization",
      );
      return isNoneAuth && hasAuthorizationHeader ? Boolean(oauthPassthroughRaw ?? mcpСервер.oauth_passthrough) : false;
    })(),
    // ``dcr_bridge`` is only meaningful for the client-forwarded token
    // modes (true_passthrough / oauth_delegate). The field is
    // conditionally rendered so the value drops выход of the form on
    // auth_type change; force false for any other configuration to avoid
    // persisting a stale ``true`` that would silently re-activate if the
    // mode is later switched back.
    dcr_bridge: isClientForwardedТокенРежим(restЗначениеs.auth_type)
      ? Boolean(dcrBridgeRaw ?? mcpСервер.dcr_bridge)
      : false,
    ...(restЗначениеs.auth_type === AUTH_TYPE.OAUTH2 && restЗначениеs.oauth_flow_type
      ? {
          oauth2_flow:
            restЗначениеs.oauth_flow_type === OAUTH_FLOW.M2M ? MCP_OAUTH2_FLOW_M2M : MCP_OAUTH2_FLOW_INTERACTIVE,
        }
      : {}),
    // Include token_validation when it is set (non-null) or when clearing an existing value
    ...(tokenValidation !== null || mcpСервер.token_validation ? { token_validation: tokenValidation } : {}),
  };

  const includeУчётные данные = restЗначениеs.auth_type && AUTH_TYPES_REQUIRING_CREDENTIALS.includes(restЗначениеs.auth_type);

  // Client-forwarded rows persist ONLY the declared app; strip any token material lingering in the
  // form (e.g. from a prior oauth2 authorize this session) so it can never reach the row.
  const submitУчётные данные = isClientForwardedТокенРежим(restЗначениеs.auth_type)
    ? preservedAdminУчётные данные(credentialsPayload)
    : credentialsPayload;

  if (includeУчётные данные && submitУчётные данные && Object.keys(submitУчётные данные).length > 0) {
    payload.credentials = submitУчётные данные;
  }

  // Explicit removal of a saved app for the client-forwarded modes, applied AFTER the filter so it
  // always wins. Blank fields are the keep-existing convention (the backend merges partial
  // credential updates), so removal must be an explicit-null write: encrypt skips nulls and the
  // merge overrides the stored keys, returning the server to dynamic client registration.
  if (removeStoredПриложение && isClientForwardedТокенРежим(restЗначениеs.auth_type)) {
    payload.credentials = { client_id: null, client_secret: null };
  }
  return { kind: "ok" as const, payload };
};

const clone = <T>(v: T): T => structuredClone(v);

describe("buildEditСерверPayload matches the pre-extraction handleSave body", () => {
  it.each(CASES.map((c) => [c.label, c] as const))("%s", (_label, testCase) => {
    const ui: EditСерверUiState = { ...baseUi, ...testCase.ui } as EditСерверUiState;
    const legacy = legacyBuild(clone(testCase.values), clone(ui) as EditСерверUiState);
    const next = buildEditСерверPayload(clone(testCase.values), clone(ui) as EditСерверUiState);

    expect(next.kind).toBe(legacy.kind);
    if (legacy.kind !== "ok" || next.kind !== "ok") {
      expect(next).toStrictEqual(legacy);
      return;
    }
    expect(next.payload).toStrictEqual(legacy.payload);
    expect(Object.keys(next.payload)).toStrictEqual(Object.keys(legacy.payload));
    expect(JSON.stringify(next.payload)).toBe(JSON.stringify(legacy.payload));
  });
});

const EDIT_FORM_VALUES: EditСерверFormЗначениеs = {
  server_name: "srv",
  alias: "srv_alias",
  description: "a server",
  transport: "http",
  url: "https://example.com/mcp",
  auth_type: "none",
  mcp_access_groups: [],
  extra_headers: [],
  static_headers: [],
  env_vars: [],
  allow_all_keys: false,
  available_on_public_internet: true,
};

describe("buildEditСерверPayload wire contract", () => {
  it("carries an edited alias and the server identifier onto the wire", () => {
    const result = buildEditСерверPayload({ ...EDIT_FORM_VALUES, alias: "renamed" }, baseUi);

    expect(result).toMatchObject({ kind: "ok", payload: { server_id: "srv_1", alias: "renamed" } });
  });

  it.fails(
    "sends description as an explicit null when the field is cleared (expected to fail until the forms revamp, tri-state PATCH tracker: today the cleared field reaches the wire as an empty string)",
    () => {
      const result = buildEditСерверPayload({ ...EDIT_FORM_VALUES, description: "" }, baseUi);

      expect(result).toMatchObject({ kind: "ok", payload: { description: null } });
    },
  );

  it.fails(
    "sends only the server identifier and the edited alias (expected to fail until the forms revamp, tri-state PATCH tracker)",
    () => {
      const result = buildEditСерверPayload({ ...EDIT_FORM_VALUES, alias: "renamed" }, baseUi);

      expect(result).toStrictEqual({ kind: "ok", payload: { server_id: "srv_1", alias: "renamed" } });
    },
  );
});

void ADMIN_CONFIG_CREDENTIAL_KEYS;
void AUTH_TYPE;
void AUTH_TYPES_REQUIRING_CREDENTIALS;
void MCP_OAUTH2_FLOW_INTERACTIVE;
void MCP_OAUTH2_FLOW_M2M;
void OAUTH_FLOW;
void TOOL_DISPLAY_NAME_PATTERN;
void TRANSPORT;
void isClientForwardedТокенРежим;
void normalizeEnvVars;
void preservedAdminУчётные данные;
export type { MCPСервер };
